=== nerineaoi/DAW/1st-Year/Lenguaje-de-Marcas/UD4-Definicion-de-Esquemas-y-Vocabularios-en-Lenguajes-de-Marcas/libreria.dtd
<!ELEMENT libreria (categoria+)>

<!ELEMENT categoria (libro+)>
<!ATTLIST categoria nombre CDATA #REQUIRED>

<!ELEMENT libro EMPTY>
<!ATTLIST libro 
    titulo CDATA #REQUIRED
    autor CDATA #REQUIRED
    publicado CDATA #REQUIRED
    editorial CDATA #REQUIRED>

=== nerineaoi/DAW/1st-Year/Lenguaje-de-Marcas/UD4-Definicion-de-Esquemas-y-Vocabularios-en-Lenguajes-de-Marcas/libreria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria SYSTEM "libreria.dtd">

<libreria>
    <!-- Categoría: Fantasía -->
    <categoria nombre="Fantasía">
        
        <libro titulo="Harry Potter y la Piedra Filosofal" autor="J.K. Rowling" publicado="1999" editorial="Salamandra" sinopsis="En esta primera obra se introducen la mayoría de los personajes principales de la serie, así como muchos de los lugares donde se desarrollará la acción. Se narran los primeros pasos de Harry en el mundo de la magia, así como su primer enfrentamiento con Voldemort, quien en su búsqueda de la inmortalidad quiere obtener el poder de la piedra filosofal y posee al profesor de defensa contra las artes oscuras." imagen="img/harry.jpg" />
        <libro titulo="El Hobbit" autor="J.R.R. Tolkien" publicado="1982" editorial="Ediciones Minotauro" sinopsis="Bilbo Bolsón es un hobbit respetable que disfruta de su vida tranquila hasta que el mago Gandalf le dice que se prepare para una aventura. Gandalf ha ofrecido a Bilbo a unirse a un grupo de enanos que van a una montaña lejana. Los enanos quieren recuperar su oro de un dragón llamado Smaug." imagen="img/hobbit.jpg" />
        <libro titulo="Juego de Tronos" autor="George R.R. Martin" publicado="2002" editorial="DEBOLSILLO" sinopsis="La historia principal narra la lucha de poder por el Trono de Hierro entre las grandes Casas de Poniente tras la muerte del Rey Robert en Juego de Tronos. El heredero aparente de Robert, Joffrey, de 13 años, es proclamado inmediatamente rey gracias a las maquinaciones de su madre, la reina Cersei Lannister." imagen="img/jdt.jpg" />
        <libro titulo="Una Corte de Rosas y Espinas" autor="Sarah J. Maas" publicado="2024" editorial="Crossbooks" sinopsis="Cuando la cazadora de diecinueve años llamada Feyre mata a un lobo en el bosque, una criatura misteriosa parecida a una bestia llega para cobrar su recompensa. Es así como Feyre es capturada y llevada a una tierra mágica que creía que solo existir en los cuentos de hadas." imagen="img/ucdrye.jpg" />

    </categoria>

    <!-- Categoría: Ciencia Ficción -->
    <categoria nombre="Ciencia Ficción">
        <libro titulo="Dune" autor="Frank Herbert" publicado="1975" editorial="Acervo" sinopsis="Dune relata la historia del planeta desértico Arrakis, única fuente de melange, la especia necesaria para el viaje interestelar y que además garantiza longevidad y poderes psíquicos. La administración de Arrakis es transferida por el emperador de la noble Casa de Harkonnen a la Casa Atreides." imagen="img/dune.jpg" />        
        <libro titulo="Los Juegos del Hambre" autor="Suzanne Collins" publicado="2009" editorial="Molino" sinopsis="Un pasado de guerras ha dejado los 12 distritos que dividen Panem bajo el poder tiránico del “Capitolio”. Sin libertad y en la pobreza, nadie puede salir de los límites de su distrito. Sólo una chica de 16 años, Katniss Everdeen, osa desafiar las normas para conseguir comida." imagen="img/ljdh.jpg" />
        <libro titulo="Uglies (Traición 1)" autor="Scott Westerfeld" publicado="2008" editorial="Montena" sinopsis="Cuenta la historia de una adolescente, Tally Youngblood, que se rebela contra la conformidad impuesta por la sociedad después de que sus amigos Shay y David le muestran las desventajas de convertirse en una Pretty" imagen="img/uglies.webp" />
        <libro titulo="Silo: Wool" autor="Hugh Howey" publicado="2023" editorial="Minotauro" sinopsis="El primer libro de la aclamada trilogía, best seller del New York Times, Wool es la historia de la humanidad luchando por sobrevivir . El mundo exterior se ha vuelto tóxico, la visión de él es limitada, hablar de él está prohibido. Los restos de la humanidad viven bajo tierra en un solo silo. Pero siempre hay quienes tienen esperanza, quienes sueñan." imagen="img/wool.jpg" />
        
    </categoria>

        <!-- Categoría: Terror -->
    <categoria nombre="Terror">
        <libro titulo="Entrevista con el Vampiro" autor="Anne Rice" publicado="1977" editorial="Ediciones B" sinopsis="A través de la entrevista de Louis con un joven reportero, Anne Rice nos invita a conocer el tormento existencial de un vampiro que busca la verdad en un mundo donde la belleza y la decadencia conviven en una lucha perpetua." imagen="img/ecev.jpg" />
        <libro titulo="La casa infernal" autor="Richard Matheson" publicado="1971" editorial="Minotauro" sinopsis="La historia trata de cuatro personas: el doctor Lionel Barrett, un físico interesado en la parapsicología, su esposa Edith y dos médiums —Florence Tanner, espiritualista y médium mental, y Benjamin Franklin Fischer, médium físico—, que son contratados por un millonario moribundo, William Reinhardt Deutsch, para investigar la posibilidad de que exista vida después de la muerte. Para llevar a cabo su misión deben entrar en la tristemente célebre Casa Belasco en Maine, considerada como la casa más embrujada del mundo. La casa se llama «Hell House» debido a los horribles actos de blasfemia y perversión ocurridos bajo la influencia silenciosa de Emeric Belasco. Fischer es el único sobreviviente de un intento fallido de investigación treinta años antes. La novela combina terror sobrenatural con misterio, los investigadores intentan descubrir los fantasmas de la casa mientras su cordura se ve sutilmente socavada por la siniestra influencia sobrenatural." imagen="img/infer.jpg"/>
        <libro titulo="El Exorcista" autor="William Peter Blatty" publicado="1971" editorial="Booket" sinopsis="El libro que inspiró la película homónima de culto. Basada en un hecho real, ocurrido en la década de los cuarenta del siglo pasado, la protagonista es una niña de apenas once años que sufre terribles transformaciones, sobre todo en su comportamiento." imagen="img/exor.jpg" />
        <libro titulo="La llamada de Cthulhu" autor="H.P. Lovecraft" publicado="1993" editorial="Valdemar" sinopsis="El narrador, heredero de su legado, se vuelca en la interpretación arqueológica de un bajorrelieve que va acompañado de un texto en una lengua desconocida que hace referencia a un culto secreto del que parece ser un dios olvidado y extraterrestre con el nombre de «Cthulhu»." imagen="img/lldc.jpg" />

    </categoria>

    <categoria nombre="Misterio/Thriller">
        <libro titulo="Ángeles y Demonios" autor="Dan Brown" publicado="2017" editorial="Planeta" sinopsis="Cuando el simbologista de Harvard Robert Langdon descubre el resurgimiento de una antigua hermandad conocida como los Illuminati, vuela a Roma para advertir al Vaticano, el enemigo más odiado de los Illuminati ." imagen="img/ayd.jpg" />
        <libro titulo="El Silencio de los Corderos" autor="Thomas Harris" publicado="1988" editorial="Grijalbo" sinopsis="Esta es la estremecedora historia de Clarice Starling, una ambiciosa joven estudiante del FBI y quien recibe el encargo de investigar el caso de un asesino serial de mujeres apodado, Buffalo Bill." imagen="img/esdlc.jpg" />
        <libro titulo="El Alienista" autor="Caleb Carr" publicado="2013" editorial="Ediciones B" sinopsis="La novela, El alienista, de Caleb Carr es un complejo thriller psicológico ambientado en 1896, que sigue a un alienista, el Dr. Lazlow Kreizler, y a otros cuatro miembros de un equipo que él reúne para intentar perfilar psicológicamente a un asesino desconocido que está asesinando y mutilando a niños prostitutos en la ciudad de Nueva York." imagen="img/ea.jpg" />
        <libro titulo="No Mientas" autor="Arturo del Burgo" publicado="2025" editorial="NEWTON COMPTON EDITORES" sinopsis="El cuerpo de Daniela aparece sin vida en un hotel a las afueras de San Sebastián. Esperaba a su amante en la habitación cuando la sorprendió una muerte brutal y violenta: esposada con los ojos vendados para simular un inocente juego sexual, y apuñalada.La inspectora Adriana Collante acude a la escena del crimen para hacerse cargo de la investigación. Pero tambien lo hace un periodista que ha recibido un correo del asesino con la hora y la fecha del lugar del homicidio. Así se anuncia la muerte de la mujer, la primera víctima que ha caído en las garras de este sociópata. Lo que a simple vista parecía un crimen pasional, una venganza, se convierte enseguida en el primero de una macabra serie de homicidios narrados y publicados en una página web minutos antes de que ocurran.Arranca entonces una carrera trepidante y contrarreloj por atrapar al asesino antes de que obtenga el exito y la fama que persigue con cada muerte anunciada." imagen="img/nomientas.jpeg" />
    
    </categoria>
    
</libreria>
